import React from 'react';
const Footer = () => {
    return (React.createElement("footer", { className: "bg-purple-1000 text-gray-400 py-4  mt-auto" },
        React.createElement("div", { className: "container mx-auto px-4" },
            React.createElement("div", { className: "flex flex-col md:flex-row justify-between items-center md:items-start mb-4 " },
                React.createElement("div", { className: "flex items-center space-x-6" },
                    React.createElement("img", { src: "src/assets/LogoAkai.png", alt: "AkaiStudioLogo", className: "h-8" }),
                    React.createElement("ul", { className: "flex flex-wrap space-x-4 justify-center md:justify-start" },
                        React.createElement("li", null,
                            React.createElement("a", { href: "#", className: "text-red-700 hover:text-white text-sm" }, "Prensa")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#", className: "text-red-700 hover:text-white text-sm" }, "Seguridad")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#", className: "text-red-700 hover:text-white text-sm" }, "Legal")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#", className: "text-red-700 hover:text-white text-sm" }, "Aviso de Privacidad")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#", className: "text-red-700 hover:text-white text-sm" }, "T\u00E9rminos de Servicio")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#", className: "text-red-700 hover:text-white text-sm" }, "Asistencia")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#", className: "text-red-700 hover:text-white text-sm" }, "Verificar en L\u00EDnea")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#", className: "text-red-700 hover:text-white text-sm" }, "Accesibilidad")))),
                React.createElement("div", { className: "flex space-x-4 mt-4 md:mt-0 justify-center" },
                    React.createElement("a", { href: "#", className: "hover:text-white" },
                        React.createElement("img", { src: "src/assets/youtube.png", alt: "youtube", className: "w-12 h-12" })),
                    React.createElement("a", { href: "#", className: "hover:text-white" },
                        React.createElement("img", { src: "src/assets/tiktok.png", alt: "tiktok", className: "w-12 h-12" })),
                    React.createElement("a", { href: "#", className: "hover:text-white" },
                        React.createElement("img", { src: "src/assets/linkidin.png", alt: "LinkedIn", className: "w-12 h-12" })),
                    React.createElement("a", { href: "#", className: "hover:text-white" },
                        React.createElement("img", { src: "src/assets/instagram.png", alt: "instagram", className: "w-12 h-12" })))),
            React.createElement("div", { className: "flex flex-col md:flex-row justify-between items-center border-t border-gray-700 pt-4" },
                React.createElement("p", { className: "text-sm text-gray-400 text-center md:text-left" }, "Preferencias de cookies | \u00A9 2024 Akai Studio, Inc. Todos los derechos reservados."),
                React.createElement("a", { href: "#top", className: "text-sm text-gray-400 hover:text-white mt-4 md:mt-0" }, "IR AL INICIO \u25B2")))));
};
export default Footer;
