import React from 'react';
const Contact = () => {
    return (React.createElement("div", { className: "w-screen min-h-screen flex flex-col items-center justify-center bg-gradient-to-b from-black to-gray-900 px-6 pt-[150px] overflow-hidden" },
        React.createElement("div", { className: "text-center mb-10" },
            React.createElement("h1", { className: "text-3xl font-extrabold text-red-500" }, "Contacto"),
            React.createElement("p", { className: "text-gray-300 mt-2" }, "\u00BFTienes alguna pregunta o propuesta? Cont\u00E1ctanos.")),
        React.createElement("section", { className: "w-full flex justify-center" },
            React.createElement("form", { className: "bg-gray-800 bg-opacity-40 p-6 rounded-lg shadow-lg border border-gray-600 w-full max-w-md" },
                React.createElement("div", { className: "mb-4" },
                    React.createElement("label", { className: "block text-white font-semibold mb-2" }, "Nombre"),
                    React.createElement("input", { type: "text", className: "w-full p-3 rounded bg-gray-700 text-white focus:outline-none focus:ring-2 focus:ring-red-500", placeholder: "Tu nombre" })),
                React.createElement("div", { className: "mb-4" },
                    React.createElement("label", { className: "block text-white font-semibold mb-2" }, "Correo Electr\u00F3nico"),
                    React.createElement("input", { type: "email", className: "w-full p-3 rounded bg-gray-700 text-white focus:outline-none focus:ring-2 focus:ring-red-500", placeholder: "correo@ejemplo.com" })),
                React.createElement("div", { className: "mb-4" },
                    React.createElement("label", { className: "block text-white font-semibold mb-2" }, "Mensaje"),
                    React.createElement("textarea", { className: "w-full p-3 h-32 rounded bg-gray-700 text-white focus:outline-none focus:ring-2 focus:ring-red-500", placeholder: "Escribe tu mensaje aqu\u00ED..." })),
                React.createElement("button", { className: "w-full py-3 bg-red-700 text-white font-semibold rounded-full text-sm hover:bg-red-900 transition" }, "Enviar Mensaje"))),
        React.createElement("div", { className: "text-gray-300 space-y-4 text-left max-w-md mt-10 mb-20" },
            React.createElement("h2", { className: "text-2xl font-bold text-red-500" }, "Informaci\u00F3n de Contacto"),
            React.createElement("p", null,
                React.createElement("strong", null, "Email:"),
                " contacto@tuempresa.com"),
            React.createElement("p", null,
                React.createElement("strong", null, "Tel\u00E9fono:"),
                " +57 123 456 7890"),
            React.createElement("p", null,
                React.createElement("strong", null, "Ubicaci\u00F3n:"),
                " Ciudad, Pa\u00EDs"))));
};
export default Contact;
